name: AMI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Zip folder creation
      run: |
        zip -r webapp.zip . -x ".git*" ".github*" "node_modules*"

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Set .env file
      run: |
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} >> .env


    - name: Setup Packer
      run: |
        curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
        rm -rf packer
        unzip packer.zip
        sudo mv packer /usr/local/bin/


    - name: Build AMI
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      run: |
          cd pkr
          packer init aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
          packer build aws-debian.pkr.hcl
    
    - name: Retrieve AMI ID
      run: |
        AMI_ID=$(jq -r '.builds[0].artifact_id' manifest.json | cut -d ':' -f 2)
        echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
      working-directory: pkr

    - name: Share AMI with DEMO Account
      run: |
        DEMO_ACCOUNT_ID="704056066364"
        aws ec2 modify-image-attribute --image-id ${{ env.AMI_ID }} --launch-permission "Add=[{UserId=$DEMO_ACCOUNT_ID}]"
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AMI_ID: ${{ env.AMI_ID }}

    - name: Configure AWS Credentials for Demo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Retrieve Launch Template ID
      run: |
        LT_ID=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[?contains(LaunchTemplateName, `asg_launch_temp`) == `true`].LaunchTemplateId' --output text)
        if [ -z "$LT_ID" ]; then
          echo "LT_ID not found" >> $GITHUB_ENV
          exit 1
        else
          echo "LT_ID=$LT_ID" >> $GITHUB_ENV
        fi

    - name: Retrieve Auto Scaling Group Name
      run: |
        ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[?contains(AutoScalingGroupName, `webappASG`) == `true`].AutoScalingGroupName' --output text)
        if [ -z "$ASG_NAME" ]; then
          echo "ASG_NAME not found" >> $GITHUB_ENV
          exit 1
        else
          echo "ASG_NAME=$ASG_NAME" >> $GITHUB_ENV
        fi

    - name: Create New Launch Template Version for Demo
      if: env.ASG_NAME != 'ASG_NAME not found' && env.LT_ID != 'LT_ID not found'
      run: |
        NEW_LT_VERSION=$(aws ec2 create-launch-template-version --launch-template-id ${{ env.LT_ID }} --source-version '$Latest' --launch-template-data '{"ImageId": "${{ env.AMI_ID }}"}' --query 'LaunchTemplateVersion.VersionNumber' --output text)
        echo "NEW_LT_VERSION=$NEW_LT_VERSION" >> $GITHUB_ENV


    - name: Refresh instances in Demo account
      if: env.ASG_NAME != 'ASG_NAME not found' && env.LT_ID != 'LT_ID not found'
      run: |
        aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ env.ASG_NAME }}

    - name: Wait for instance refresh completion
      if: env.ASG_NAME != 'ASG_NAME not found' && env.LT_ID != 'LT_ID not found'
      run: |
        while true; do
              status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ env.ASG_NAME }} --query 'InstanceRefreshes[0].Status' --output text)
              if [ "$status" = "Successful" ]; then
                echo "Instance refresh completed successfully"
                break
              elif [[ $status == "Failed" ]]; then
                echo "Instance refresh failed"
                exit 1
              else
                echo "Waiting for instance refresh..."
                sleep 30
              fi
          done