name: AMI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Setup Packer
      run: |
        curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
        rm -f packer
        unzip -y packer.zip
        sudo mv packer /usr/local/bin/


    - name: Build AMI
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: packer build aws-debian.pkr.hcl

    - name: Retrieve AMI ID
      id: retrieve-ami-id
      run: |
        AMI_ID=$(aws ec2 describe-images --filters "Name=tag:BuiltBy,Values=GitHubActions-${GITHUB_RUN_ID}" --query "Images[0].ImageId" --output text)
        echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV

    - name: Share AMI with DEMO Account
      run: |
        DEMO_ACCOUNT_ID="704056066364"
        aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId=$DEMO_ACCOUNT_ID}]"