name: Packer Validate

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip folder creation
        run: |
          zip -r webapp.zip . -x ".git*" ".github*" "node_modules*"

      - name: List Directory Contents After Zip
        run: |
          ls -al
          pwd

      - name: Setup Packer
        run: |
          curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
          rm -rf packer
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: Initialize Packer
        run: |
          cd pkr
          packer init aws-debian.pkr.hcl

      - name: Packer Format Check
        run: |
          cd pkr
          packer fmt -check aws-debian.pkr.hcl

      - name: Packer Validate
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          cd pkr
          packer validate aws-debian.pkr.hcl

