name: Packer Validate

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip folder creation
        run: |
          zip -r webapp.zip . -x ".git*" ".github*" "node_modules*"

      - name: List Directory Contents After Zip
        run: |
          ls -al
          pwd

      - name: Setup Packer
        run: |
          curl -Lo packer.zip https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip
          rm -rf packer
          unzip packer.zip
          sudo mv packer /usr/local/bin/

      - name: Validate Template
        run: |
          set -x
          cd pkr
          packer init aws-debian.pkr.hcl
          packer fmt -check aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
