name: Packer Validate

on:
  [pull_request]


jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip folder creation
        run: |
          mkdir cloud_assign
          zip -r webapp . -x ".git*" ".github*" "node_modules*" 
          mv webapp.zip cloud_assign

      - name: List Directory Contents After Zip
        run: |
          ls -al
          ls cloud_assign

      - name: Validate Template
        run: |
          cd pkr
          packer init aws-debian.pkr.hcl
          packer fmt aws-debian.pkr.hcl
          packer validate aws-debian.pkr.hcl
